#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# shellcheck source=/dev/null
source "$REPO_ROOT/scripts/testnet/lib_public_bridge_env.sh"

RUN_ID="${AEGISLINK_PUBLIC_BACKEND_RUN_ID:-$(date +%Y%m%d-%H%M%S)}"
HOME_DIR="${AEGISLINK_PUBLIC_BACKEND_HOME_DIR:-/tmp/aegislink-mainnet-home-$RUN_ID}"
RUNTIME_DIR="${AEGISLINK_PUBLIC_BACKEND_RUNTIME_DIR:-/tmp/aegislink-mainnet-backend-$RUN_ID}"
READY_FILE="$HOME_DIR/data/demo-node-ready.json"
NODE_LOG="$RUNTIME_DIR/node.log"
RELAYER_LOG="$RUNTIME_DIR/relayer.log"
REPLAY_STORE="$RUNTIME_DIR/replay.json"
ATTESTATION_STATE="$RUNTIME_DIR/attestations.json"
PATH_NAME="${AEGISLINK_PUBLIC_BACKEND_RLY_PATH_NAME:-live-osmo-mainnet-$RUN_ID}"
DESTINATION_LCD_BASE_URL="${AEGISLINK_RELAYER_DESTINATION_LCD_BASE_URL:-https://lcd.osmosis.zone}"
DESTINATION_RPC_ADDR="${AEGISLINK_PUBLIC_BACKEND_DESTINATION_RPC_ADDR:-https://rpc.osmosis.zone:443}"
DESTINATION_GRPC_ADDR="${AEGISLINK_PUBLIC_BACKEND_DESTINATION_GRPC_ADDR:-https://grpc.osmosis.zone:443}"
DESTINATION_CHAIN_NAME="${AEGISLINK_PUBLIC_BACKEND_DESTINATION_CHAIN_NAME:-osmosis-1}"
DESTINATION_CHAIN_ID="${AEGISLINK_PUBLIC_BACKEND_DESTINATION_CHAIN_ID:-osmosis-1}"
DESTINATION_ACCOUNT_PREFIX="${AEGISLINK_RLY_DESTINATION_ACCOUNT_PREFIX:-osmo}"
DESTINATION_GAS_PRICE_DENOM="${AEGISLINK_RLY_DESTINATION_GAS_PRICE_DENOM:-uosmo}"
DESTINATION_GAS_PRICE_AMOUNT="${AEGISLINK_RLY_DESTINATION_GAS_PRICE_AMOUNT:-0.025}"
OSMOSIS_KEY_NAME="${AEGISLINK_RLY_OSMOSIS_MAINNET_KEY_NAME:-osmosis-mainnet-relayer-key}"
OSMOSIS_MNEMONIC="${AEGISLINK_RLY_OSMOSIS_MAINNET_MNEMONIC:-}"
RLY_TIMEOUT_SECONDS="${AEGISLINK_PUBLIC_BACKEND_RLY_TIMEOUT_SECONDS:-45}"
LINK_RETRIES="${AEGISLINK_PUBLIC_BACKEND_RLY_LINK_RETRIES:-3}"
LINK_RETRY_DELAY_SECONDS="${AEGISLINK_PUBLIC_BACKEND_RLY_LINK_RETRY_DELAY_SECONDS:-5}"
LINK_TIMEOUT_DURATION="${AEGISLINK_PUBLIC_BACKEND_RLY_LINK_TIMEOUT_DURATION:-5m}"
LINK_MAX_RETRIES="${AEGISLINK_PUBLIC_BACKEND_RLY_LINK_MAX_RETRIES:-6}"
LINK_BLOCK_HISTORY="${AEGISLINK_PUBLIC_BACKEND_RLY_LINK_BLOCK_HISTORY:-5}"
NEUTRON_CHAIN_NAME="${AEGISLINK_PUBLIC_BACKEND_NEUTRON_CHAIN_NAME:-neutron-1}"
NEUTRON_CHAIN_ID="${AEGISLINK_PUBLIC_BACKEND_NEUTRON_CHAIN_ID:-neutron-1}"
NEUTRON_RPC_ADDR="${AEGISLINK_PUBLIC_BACKEND_NEUTRON_RPC_ADDR:-https://rpc-kralum.neutron-1.neutron.org:443}"
NEUTRON_GRPC_ADDR="${AEGISLINK_PUBLIC_BACKEND_NEUTRON_GRPC_ADDR:-https://grpc-kralum.neutron-1.neutron.org:443}"
NEUTRON_LCD_BASE_URL="${AEGISLINK_PUBLIC_BACKEND_NEUTRON_LCD_BASE_URL:-https://rest-kralum.neutron-1.neutron.org}"
NEUTRON_ACCOUNT_PREFIX="${AEGISLINK_RLY_NEUTRON_ACCOUNT_PREFIX:-neutron}"
NEUTRON_GAS_PRICE_DENOM="${AEGISLINK_RLY_NEUTRON_GAS_PRICE_DENOM:-untrn}"
NEUTRON_GAS_PRICE_AMOUNT="${AEGISLINK_RLY_NEUTRON_GAS_PRICE_AMOUNT:-0.025}"
NEUTRON_GAS_ADJUSTMENT="${AEGISLINK_RLY_NEUTRON_GAS_ADJUSTMENT:-2.0}"
NEUTRON_KEY_NAME="${AEGISLINK_RLY_NEUTRON_MAINNET_KEY_NAME:-neutron-mainnet-relayer-key}"
NEUTRON_MNEMONIC="${AEGISLINK_RLY_NEUTRON_MAINNET_MNEMONIC:-}"
NEUTRON_PATH_NAME="${AEGISLINK_PUBLIC_BACKEND_NEUTRON_PATH_NAME:-live-ntrn-mainnet-$RUN_ID}"
NEUTRON_ROUTE_ID="neutron-mainnet-wallet"
PERSISTENT_RLY_HOME="${AEGISLINK_RELAYER_RLY_HOME:-$HOME/.aegislink-mainnet-rly}"
GOCACHE="${GOCACHE:-/tmp/aegislink-gocache}"
STATUS_FILE="$RUNTIME_DIR/status.json"
CURRENT_STATUS_FILE="${AEGISLINK_PUBLIC_BACKEND_CURRENT_STATUS_FILE:-/tmp/aegislink-mainnet-backend-current.json}"

source_required_env() {
  local env_file="$1"
  if [[ ! -f "$env_file" ]]; then
    echo "missing required env file: $env_file" >&2
    exit 1
  fi
  set -a
  # shellcheck source=/dev/null
  source "$env_file"
  set +a
}

# Source mainnet env overrides if present
if [[ -f "$REPO_ROOT/.env.mainnet.local" ]]; then
  source_required_env "$REPO_ROOT/.env.mainnet.local"
  OSMOSIS_MNEMONIC="${AEGISLINK_RLY_OSMOSIS_MAINNET_MNEMONIC:-$OSMOSIS_MNEMONIC}"
  OSMOSIS_KEY_NAME="${AEGISLINK_RLY_OSMOSIS_MAINNET_KEY_NAME:-$OSMOSIS_KEY_NAME}"
  NEUTRON_MNEMONIC="${AEGISLINK_RLY_NEUTRON_MAINNET_MNEMONIC:-$NEUTRON_MNEMONIC}"
  NEUTRON_KEY_NAME="${AEGISLINK_RLY_NEUTRON_MAINNET_KEY_NAME:-$NEUTRON_KEY_NAME}"
fi

OSMOSIS_ROUTE_ID="osmosis-mainnet-wallet"

echo "AegisLink mainnet backend - RUN_ID=$RUN_ID"
echo "Osmosis mainnet: $DESTINATION_RPC_ADDR"
echo "Neutron mainnet: $NEUTRON_RPC_ADDR"
echo "Runtime dir: $RUNTIME_DIR"
